### PR TITLE
Bug fixes, bring back line numbers

### PR DESCRIPTION
**Pull request by mds1**
Fixes a few things that broke in #8, and reintroduces line numbers for findings. See commit messages for details

### CODE REVIEW

**Review by jferas — APPROVED** [review]
Looks good.. nice to have the line numbers back.. and parsing is so elegant with solang.

**Review by apbendi — COMMENTED** [review]
This worked, inasmuch as it properly ignored a contract in my `script/` dir that was not actually a script.

It also failed when I commented out `run` from a contract that *is* a script. However, the error message it produced gave no hint as to why:

```
gitcoin-governor % scopelintl check
error: Formatting validation failed, run `scopelint fmt` to f
```

versus the current output:

```
% scopelint check
Invalid script interface in ./script/Deploy.s.sol
error: Naming conventions failed, see details above
error: Formatting validation failed, run `scopelint fmt` to fix
```

**Review by davidlaprade — APPROVED** [review]
LGTM, and ran without issue on flex voting 👍

**Review by apbendi — APPROVED** [review]
Looks good to me! Seems to work when run against the Gitcoin Governor codebase.

One minor nit is that the error message for script naming says " Scripts must have a single public method named `run`" but it also seems to allow a public `setUp` method. Perhaps worth updating to say that? Will leave up to you—otherwise good to merge.

**Pull request merged**
